# Generated by Django 5.0.7 on 2024-07-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_alter_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Critical", "Critical"),
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                    ("Optional", "Optional"),
                ],
                default="Medium",
                max_length=255,
            ),
        ),
    ]
