# Generated by Django 5.0.7 on 2024-07-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0007_alter_task_assignees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="task_manager.position",
            ),
            preserve_default=False,
        ),
    ]
