# Generated by Django 5.0.7 on 2024-07-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0009_alter_task_task_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("importance", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["importance"],
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="task_manager.taskpriority",
            ),
        ),
    ]
