# Generated by Django 5.0.7 on 2024-07-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0010_taskpriority_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
    ]
