# Generated by Django 5.0.7 on 2024-07-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0011_alter_task_description_alter_task_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
